--- # logging config for slack hooks in yaml

version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  verbose:
    format: "%(asctime)s - %(filename)s - %(module)s - %(funcName)s - %(process)d - %(thread)d - %(name)s - %(levelname)s - %(message)s"
handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: verbose
    filename: debug.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: verbose
    filename: info.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: verbose
    filename: error.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
<%if ( useSentry == true) { %>
  sentry_handler:
    class: raven.handlers.logging.SentryHandler
    level: ERROR
    dsn: # supplied at runtime via env variable SENTRY_DSN
<% } %>
loggers:
  default:
    level: ERROR
    handlers: [console_handler]
    propagate: no
root:
  level: DEBUG
  handlers:
    - console_handler
    - debug_file_handler
    - info_file_handler
    - error_file_handler
<%if ( useSentry == true ) { %>
    - sentry_handler
<% } %>
