"""
Django settings for <%= projectName %>, a dockerized django rest framework
project.

Generated by the yeoman generator-django-rest-docker generator for Django 1.10.
"""
import os

import dj_database_url
import yaml


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get('DJANGO_DEBUG', 0))

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'django_nose',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '<%= projectName %>.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '<%= projectName %>.wsgi.application'


################
# The database #
################

DATABASES = {'default': dj_database_url.config(conn_max_age=500)}



# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = os.environ.get('DJANGO_LANGUAGE_CODE', 'en-us')

TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'UTC')

USE_I18N = bool(os.environ.get('DJANGO_USE_I18N', 1))

USE_L10N = bool(os.environ.get('DJANGO_USE_L10N', 1))

USE_TZ = bool(os.environ.get('DJANGO_USE_TZ', 1))


#############################
# Static file configuration #
#############################

STATIC_URL = os.environ.get('DJANGO_STATIC_URL', '/static/')

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = [
    os.path.join(PROJECT_ROOT, 'static'),
]

# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



###########
# Testing #
###########

TEST_RUNNER = 'django_nose.NoseTestSuiteRunner'

NOSE_ARGS = (
    '--cover-branches',
    '--cover-erase',
    '--cover-html',
    '--cover-html-dir=cover',
    '--cover-min-percentage=75',
    '--cover-package=<%= projectName %>',
    '--exe',
    '--logging-clear-handlers',
    '--stop',
    '--verbosity=2',
    '--with-coverage',
)

#########################
# Logging, so important #
#########################

with open(os.path.join(BASE_DIR, 'logging.yml'), 'rb') as stream:
    LOGGING = yaml.load(stream)

<%if (useSentry == true) { %>
import raven

SENTRY_DSN = os.environ.get('SENTRY_DSN')
LOGGING['handlers']['sentry_handler']['dsn'] = SENTRY_DSN

RAVEN_CONFIG = {
    'dsn': SENTRY_DSN
    # If you are using git, you can also automatically configure the
    # release based on the git info.
    'release': raven.fetch_git_sha(os.path.dirname(os.pardir)),
}
<% } %>

################################
# REST Framework Configuration #
################################

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # including for api users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ]
}

<% if ( useCelery == true ) { %>
#############################
# Celery GOT TO HAVE CELERY #
#############################

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', None)
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', None)

CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERYD_HIJACK_ROOT_LOGGER = False
<% } %>

<% if ( useLdap == true ) { %>

#########################################
# LDAP Oh Yeah, Big Time with that LDAP #
#########################################

import ldap
from django_auth_ldap.config import LDAPSearch, ActiveDirectoryGroupType

AUTH_LDAP_SERVER_URI = os.environ.get('LDAP_SERVER_URI')
AUTH_LDAP_BIND_DN = os.environ.get('LDAP_BIND_USER')
AUTH_LDAP_BIND_PASSWORD = os.environ.get('LDAP_BIND_PWD')

AUTH_LDAP_GLOBAL_OPTIONS = {
    ldap.OPT_X_TLS_REQUIRE_CERT: bool(os.environ.get('LDAP_OPT_X_TLS_REQUIRE_CERT')),
    ldap.OPT_X_TLS: bool(os.environ.get('LDAP_OPT_X_TLS')),
    ldap.OPT_X_TLS_DEMAND: bool(os.environ.get('LDAP_X_TLS_DEMAND')),
    ldap.OPT_X_TLS_CACERTDIR: os.environ.get('LDAP_OPT_X_TLS_CACERTDIR'),
}

AUTH_LDAP_USER_SEARCH = LDAPSearch(
    'cn=users,dc=usccreditunion,dc=org',
    ldap.SCOPE_SUBTREE,
    '(sAMAccountName=%(user)s)',
)

AUTH_LDAP_USER_ATTR_MAP = {
    'name': 'cn',
    'email': 'mail',
    'first_name': 'givenName',
    'last_name': 'sn',
}

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    'ou=groups,dc=usccreditunion,dc=org',
    ldap.SCOPE_SUBTREE,
    '(objectClass=group)'
)

AUTH_LDAP_GROUP_TYPE = ActiveDirectoryGroupType(name_attr='cn')
AUTH_LDAP_REQUIRE_GROUP = os.environ.get('LDAP_REQUIRE_GROUP')
AUTH_LDAP_DENY_GROUP = os.environ.get('LDAP_DENY_GROUP')

AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": os.environ.get('LDAP_USER_FLAG_GROUP_ACTIVE'),
    "is_staff": os.environ.get('LDAP_USER_FLAG_GROUP_STAFF'),
    "is_superuser": os.environ.get('LDAP_USER_FLAG_GROUP_SUPERUSER'),
}

# Cache group memberships for an hour to minimize LDAP traffic
AUTH_LDAP_CACHE_GROUPS = True
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 3600

AUTHENTICATION_BACKENDS = [
    'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
]

<% } %>
